# Generated by Django 4.1.7 on 2023-02-23 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_depositnotification_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositnotification',
            old_name='user_id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='referralrewardnotification',
            old_name='user_id',
            new_name='uid',
        ),
    ]
