FROM ruby:3.1

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

RUN mkdir /auth_service
WORKDIR /auth_service

COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY ./entrypoint.sh ./
RUN chmod +x ./entrypoint.sh
ADD . ./

ENTRYPOINT [ "./entrypoint.sh" ]