FROM ruby:3.1

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

WORKDIR /usr/src/auth-service

COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY ./entrypoint.prod.sh .
RUN chmod +x /usr/src/auth-service/entrypoint.prod.sh
ADD . ./

ENTRYPOINT [ "/usr/src/auth-service/entrypoint.prod.sh" ]