version: "3.8"

services:
  db:
    image: postgres:15.2-alpine3.17
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    
    
  server:
    build:
      context: .
      dockerfile: DOCKERFILE.prod
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -e production -p 8080 -b '0.0.0.0'"
    environment:
      - SQL_HOST=db
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_DATABASE=auth_db

    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  data: